modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Metallurgists-of-Create/Rutile/issues"
[[mods]]
modId="rutile"
version="${project.mod_version}-neoforge-mc${project.minecraft_version}"
displayName="Rutile"
displayURL="https://github.com/Metallurgists-of-Create/Rutile"
logoFile="rutile.png"
credits="Krystal"
authors="PouffyDev"
description='''
    API for easy material registry using flags.
    Also chemical compositions.
'''
[[dependencies.rutile]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.rutile]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"